image: $scf_ci_image

before_script:
  # add deployment keys
  - echo "$id_rsa_deploy_ro" >  ~/.ssh/id_rsa_deploy_ro
  - chmod 600 ~/.ssh/id_rsa_deploy_ro
  # Get scf_test_driver repo (last commit only)
  - git clone --depth 1 $scf_ci_repo_test_driver scf_test_driver

after_script:
  # remove deployment keys
  - rm ~/.ssh/id_rsa_deploy_ro


.test_pipeline:
  tags:
    - docker
  stage: test

# Test pipeline 1: STL -> STLXML -> EBU-TT -> EBU-TT-D -> EBU-TT-D-Basic-DE -> WebVTT
test_pipeline_1:
  extends: .test_pipeline
  script:
    # STL -> STLXML
    - modules/STL2STLXML/stl2stlxml.py -p -x 2_STLXML.xml misc/ci/test_pipeline_1/1_STL.stl
    - diff misc/ci/test_pipeline_1/2_STLXML.xml 2_STLXML.xml
    # STLXML -> EBU-TT (use constant date/time to make result reproducible)
    - java -cp ~/tools/SaxonEE9/saxon9ee.jar net.sf.saxon.Transform \!indent=true -s:2_STLXML.xml -xsl:modules/STLXML2EBU-TT/STLXML2EBU-TT.xslt -o:3_EBU-TT.xml -now:2018-01-01T00:00:00+00:00
    - diff misc/ci/test_pipeline_1/3_EBU-TT.xml 3_EBU-TT.xml
    # EBU-TT -> EBU-TT-D
    - java -cp ~/tools/SaxonEE9/saxon9ee.jar net.sf.saxon.Transform \!indent=true -s:3_EBU-TT.xml -xsl:modules/EBU-TT2EBU-TT-D/EBU-TT2EBU-TT-D.xslt -o:4_EBU-TT-D.xml
    - diff misc/ci/test_pipeline_1/4_EBU-TT-D.xml 4_EBU-TT-D.xml
    # EBU-TT-D -> EBU-TT-D-Basic-DE
    - java -cp ~/tools/SaxonEE9/saxon9ee.jar net.sf.saxon.Transform \!indent=true -s:4_EBU-TT-D.xml -xsl:modules/EBU-TT-D2EBU-TT-D-Basic-DE/EBU-TT-D2EBU-TT-D-Basic-DE.xslt -o:5_EBU-TT-D-Basic-DE.xml
    - diff misc/ci/test_pipeline_1/5_EBU-TT-D-Basic-DE.xml 5_EBU-TT-D-Basic-DE.xml
    # EBU-TT-D-Basic-DE -> WebVTT
    - java -cp ~/tools/SaxonEE9/saxon9ee.jar net.sf.saxon.Transform -s:5_EBU-TT-D-Basic-DE.xml -xsl:modules/EBU-TT-D-Basic-DE2WebVTT/EBU-TT-D-Basic-DE2WebVTT.xslt -o:6_WebVTT.vtt
    - diff misc/ci/test_pipeline_1/6_WebVTT.vtt 6_WebVTT.vtt

# Test pipeline 2: EBU-TT -> STLXML -> STL
test_pipeline_2:
  extends: .test_pipeline
  script:
    # EBU-TT -> STLXML (use constant date/time to make result reproducible)
    - java -cp ~/tools/SaxonEE9/saxon9ee.jar net.sf.saxon.Transform \!indent=true -s:misc/ci/test_pipeline_2/1_EBU-TT.xml -xsl:modules/EBU-TT2STLXML/EBU-TT2STLXML.xslt -o:2_STLXML.xml  -now:2020-05-08T00:00:00+00:00
    - diff misc/ci/test_pipeline_2/2_STLXML.xml 2_STLXML.xml
    # STLXML -> STL
    - ~/tools/basex/bin/basex -i 2_STLXML.xml modules/STLXML2STL/stlxml2stl_helper.xq > 3_STL.stl
    - diff misc/ci/test_pipeline_2/3_STL.stl 3_STL.stl

# Test pipeline 3: SRT -> SRTXML -> TTML (default template)
test_pipeline_3:
  extends: .test_pipeline
  script:
    # SRT -> SRTXML
    - modules/SRT2SRTXML/srt2srtxml.py -p -x 2_SRTXML.xml misc/ci/test_pipeline_3/1_SRT.srt
    - diff misc/ci/test_pipeline_3/2_SRTXML.xml 2_SRTXML.xml
    # SRTXML -> TTML (default template)
    - java -cp ~/tools/SaxonEE9/saxon9ee.jar net.sf.saxon.Transform \!indent=true -s:2_SRTXML.xml -xsl:modules/SRTXML2TTML/SRTXML2TTML.xslt -o:3_TTML.xml
    - diff misc/ci/test_pipeline_3/3_TTML.xml 3_TTML.xml

# Test pipeline 4: TTML -> SRTXML -> SRT
test_pipeline_4:
  extends: .test_pipeline
  script:
    # TTML -> SRTXML
    - java -cp ~/tools/SaxonEE9/saxon9ee.jar net.sf.saxon.Transform \!indent=true -s:misc/ci/test_pipeline_4/1_TTML.xml -xsl:modules/TTML2SRTXML/TTML2SRTXML.xslt -o:2_SRTXML.xml
    - diff misc/ci/test_pipeline_4/2_SRTXML.xml 2_SRTXML.xml
    # SRTXML -> SRT
    - java -cp ~/tools/SaxonEE9/saxon9ee.jar net.sf.saxon.Transform -s:2_SRTXML.xml -xsl:modules/SRTXML2SRT/SRTXML2SRT.xslt -o:3_SRT.srt
    - diff misc/ci/test_pipeline_4/3_SRT.srt 3_SRT.srt


# Modules
.tests:
  tags:
    - docker
  stage: test
  artifacts:
    name: "$CI_JOB_NAME"
    paths:
    # test results
    - index.html
    # provide test results only on failure
    when: on_failure

tests_STL2STLXML:
  extends: .tests
  script: scf_test_driver/ci/test_py2xml.sh STL2STLXML STL2STLXML stl2stlxml.py

tests_STLXML2STL:
  extends: .tests
  script: scf_test_driver/ci/test_stlxml2stl.sh

tests_STLXML2EBU-TT:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh STLXML2EBU-TT STLXML2EBU-TT STLXML2EBU-TT.xslt

tests_STLXML-SplitBlocks:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh STLXML-SplitBlocks STLXML-SplitBlocks STLXML-SplitBlocks.xslt

tests_EBU-TT2STLXML:
  # to be started by hand, as module has beta status!
  when: manual
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh EBU-TT2STLXML EBU-TT2STLXML EBU-TT2STLXML.xslt

tests_EBU-TT2EBU-TT-D:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh EBU-TT2EBU-TT-D EBU-TT2EBU-TT-D EBU-TT2EBU-TT-D.xslt

tests_EBU-TT-D2EBU-TT-D-Basic-DE:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh EBU-TT-D2EBU-TT-D-Basic-DE EBU-TT-D2EBU-TT-D-Basic-DE EBU-TT-D2EBU-TT-D-Basic-DE.xslt

tests_FlashDFXP2EBU-TT-D-Basic-DE:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh FlashDFXP2EBU-TT-D-Basic-DE FlashDFXP2EBU-TT-D-Basic-DE FlashDFXP2EBU-TT-D-Basic-DE.xslt

tests_STLXML_XSD:
  extends: .tests
  script: scf_test_driver/ci/test_schema.sh STLXML-XSD STLXML-XSD stlxml.xsd

tests_SRTXML_XSD:
  extends: .tests
  script: scf_test_driver/ci/test_schema.sh SRTXML-XSD SRTXML-XSD srtxml.xsd

tests_SRT2SRTXML:
  extends: .tests
  script: scf_test_driver/ci/test_py2xml.sh SRT2SRTXML SRT2SRTXML srt2srtxml.py

tests_SRTXML2SRT:
  extends: .tests
  script: scf_test_driver/ci/test_srtxml2srt.sh

tests_SRTXML2TTML:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh SRTXML2TTML SRTXML2TTML SRTXML2TTML.xslt

tests_TTML2SRTXML:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh TTML2SRTXML TTML2SRTXML TTML2SRTXML.xslt

tests_EBU-TT-D-Basic-DE2WebVTT:
  extends: .tests
  script: scf_test_driver/ci/test_ebuttdbasicde2webvtt.sh

# TT-Helper modules
tests_Helper_DFXP2TTML:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh DFXP2TTML TT-Helper/DFXP2TTML DFXP2TTML.xsl

tests_Helper_GetTTMLProfile:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh GetTTMLProfile TT-Helper/GetTTMLProfile GetTTMLProfile.xsl

tests_Helper_TT-Edit-List:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh TT-Edit-List TT-Helper/TT-Edit-List TT-Edit-List.xslt

tests_Helper_TT-Filter-Styles-No-References:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh TT-Filter-Styles-No-References TT-Helper/TT-Filter-Styles-No-References TT-Filter-Styles-No-References.xslt

tests_Helper_TTML2DFXP:
  extends: .tests
  script: scf_test_driver/ci/test_standard.sh TTML2DFXP TT-Helper/TTML2DFXP TTML2DFXP.xsl
